name: demo

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
      - 'docs/**'
    branches:
      - main
      - release-*

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }} - Node.js ${{ matrix.node-version }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-20.04]
        node-version: [14]
        include:
          - os: ubuntu-20.04
            node-version: 12
            browser: chromium
          - os: ubuntu-20.04
            node-version: 16
            browser: chromium
          - os: ubuntu-20.04
            node-version: 18
            browser: chromium
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - echo "## ${{ matrix.os }} (${{ matrix.browser }} - Node.js ${{ matrix.node-version }})" >> $GITHUB_STEP_SUMMARY
      - echo "results would go here" >> $GITHUB_STEP_SUMMARY
